export const mockRoles = [
  {
    role_id: "admin",
    role_name: "Admin",
    role_name_zh: "管理者",
    description: "具備所有管理權限，可修改系統設定。",
    action_summary: ["可設定權限", "可處理預約", "可修改系統設定"],
    staff_count: 1,
    permissions: {
      dashboard: "view",
      reservations: "full",
      customers: "full",
      services: "full",
      calendar: "view",
      staff_scheduling: "full",
      settings: "full",
    },
  },
  {
    role_id: "staff",
    role_name: "Staff",
    role_name_zh: "員工",
    description: "可處理預約與客戶服務，無系統設定權限。",
    action_summary: ["可處理預約", "可查看客戶", "可查看行事曆"],
    staff_count: 2,
    permissions: {
      dashboard: "view",
      reservations: "full",
      customers: "view",
      services: "view",
      calendar: "view",
      staff_scheduling: "view",
      settings: "no_access",
    },
  },
  {
    role_id: "viewer",
    role_name: "Viewer",
    role_name_zh: "檢視者",
    description: "僅可查看資料，無任何修改權限。",
    action_summary: ["只可查看資料", "不可修改任何內容"],
    staff_count: 0,
    permissions: {
      dashboard: "view",
      reservations: "view",
      customers: "view",
      services: "view",
      calendar: "view",
      staff_scheduling: "view",
      settings: "no_access",
    },
  },
];

